<?php

namespace App\Actions;


class ColorResolver{
    private $colorMap = [
        'bej'=> "F5F5DC",
        'beyaz'=> "FFFFFF",
        'bordo'=> "4C1C24",
        'ekru'=> "C2B280",
        'gri'=> "808080",
        'gumus'=> "C0C0C0",
        'haki'=> "F0E68C",
        'kahverengi'=> "A52A2A",
        'kirmizi-c'=> "FF0000",
        'lacivert'=> "000080",
        'mavi-c'=> "0000FF",
        'mor'=> "800080",
        'pembe'=> "FFC0CB",
        'sari'=> "FFFF00",
        'siyah'=> "000000",
        'turkuaz'=> "40E0D0",
        'turuncu'=> "FFA500",
        'yesil'=> "008000",
        'cok-renkli'=> "FFFFFF",
    
    
        'aliceblue'=> 'F0F8FF',
        'antiquewhite'=> 'FAEBD7',
        'aqua'=> '00FFFF',
        'aquamarine'=> '7FFFD4',
        'azure'=> 'F0FFFF',
        'beige'=> 'F5F5DC',
        'bisque'=> 'FFE4C4',
        'black'=> '000000',
        'blanchedalmond'=> 'FFEBCD',
        'blue'=> '0000FF',
        'blueviolet'=> '8A2BE2',
        'brown'=> 'A52A2A',
        'burlywood'=> 'DEB887',
        'cadetblue'=> '5F9EA0',
        'chartreuse'=> '7FFF00',
        'chocolate'=> 'D2691E',
        'coral'=> 'FF7F50',
        'cornflowerblue'=> '6495ED',
        'cornsilk'=> 'FFF8DC',
        'crimson'=> 'DC143C',
        'cyan'=> '00FFFF',
        'darkblue'=> '00008B',
        'darkcyan'=> '008B8B',
        'darkgoldenrod'=> 'B8860B',
        'darkgray'=> 'A9A9A9',
        'darkgreen'=> '006400',
        'darkgrey'=> 'A9A9A9',
        'darkkhaki'=> 'BDB76B',
        'darkmagenta'=> '8B008B',
        'darkolivegreen'=> '556B2F',
        'darkorange'=> 'FF8C00',
        'darkorchid'=> '9932CC',
        'darkred'=> '8B0000',
        'darknavy'=> '0B0B45',
        'darksalmon'=> 'E9967A',
        'darkseagreen'=> '8FBC8F',
        'darkslateblue'=> '483D8B',
        'darkslategray'=> '2F4F4F',
        'darkslategrey'=> '2F4F4F',
        'darkturquoise'=> '00CED1',
        'darkviolet'=> '9400D3',
        'deeppink'=> 'FF1493',
        'deepskyblue'=> '00BFFF',
        'dimgray'=> '696969',
        'dimgrey'=> '696969',
        'dodgerblue'=> '1E90FF',
        'ecru'=> 'C2B280',
        'firebrick'=> 'B22222',
        'floralwhite'=> 'FFFAF0',
        'forestgreen'=> '228B22',
        'fuchsia'=> 'FF00FF',
        'gainsboro'=> 'DCDCDC',
        'ghostwhite'=> 'F8F8FF',
        'gold'=> 'FFD700',
        'goldenrod'=> 'DAA520',
        'gray'=> '808080',
        'green'=> '008000',
        'greenyellow'=> 'ADFF2F',
        'grey'=> '808080',
        'honeydew'=> 'F0FFF0',
        'hotpink'=> 'FF69B4',
        'indianred'=> 'CD5C5C',
        'indigo'=> '4B0082',
        'ivory'=> 'FFFFF0',
        'khaki'=> 'F0E68C',
        'lavender'=> 'E6E6FA',
        'lavenderblush'=> 'FFF0F5',
        'lawngreen'=> '7CFC00',
        'lemonchiffon'=> 'FFFACD',
        'lightblue'=> 'ADD8E6',
        'lightcoral'=> 'F08080',
        'lightcyan'=> 'E0FFFF',
        'lightgoldenrodyellow'=> 'FAFAD2',
        'lightgray'=> 'D3D3D3',
        'lightgreen'=> '90EE90',
        'lightgrey'=> 'D3D3D3',
        'lightpink'=> 'FFB6C1',
        'lightsalmon'=> 'FFA07A',
        'lightseagreen'=> '20B2AA',
        'lightskyblue'=> '87CEFA',
        'lightslategray'=> '778899',
        'lightslategrey'=> '778899',
        'lightsteelblue'=> 'B0C4DE',
        'lightyellow'=> 'FFFFE0',
        'lime'=> '00FF00',
        'limegreen'=> '32CD32',
        'linen'=> 'FAF0E6',
        'magenta'=> 'FF00FF',
        'maroon'=> '800000',
        'mediumaquamarine'=> '66CDAA',
        'mediumblue'=> '0000CD',
        'mediumorchid'=> 'BA55D3',
        'mediumpurple'=> '9370D0',
        'mediumseagreen'=> '3CB371',
        'mediumslateblue'=> '7B68EE',
        'mediumspringgreen'=> '00FA9A',
        'mediumturquoise'=> '48D1CC',
        'mediumvioletred'=> 'C71585',
        'midnightblue'=> '191970',
        'mintcream'=> 'F5FFFA',
        'mistyrose'=> 'FFE4E1',
        'moccasin'=> 'FFE4B5',
        'navajowhite'=> 'FFDEAD',
        'navy'=> '000080',
        'oldlace'=> 'FDF5E6',
        'olive'=> '808000',
        'olivedrab'=> '6B8E23',
        'orange'=> 'FFA500',
        'orangered'=> 'FF4500',
        'orchid'=> 'DA70D6',
        'palegoldenrod'=> 'EEE8AA',
        'palegreen'=> '98FB98',
        'paleturquoise'=> 'AFEEEE',
        'palevioletred'=> 'DB7093',
        'papayawhip'=> 'FFEFD5',
        'peachpuff'=> 'FFDAB9',
        'peru'=> 'CD853F',
        'pink'=> 'FFC0CB',
        'plum'=> 'DDA0DD',
        'powderblue'=> 'B0E0E6',
        'purple'=> '800080',
        'red'=> 'FF0000',
        'rosybrown'=> 'BC8F8F',
        'royalblue'=> '4169E1',
        'saddlebrown'=> '8B4513',
        'salmon'=> 'FA8072',
        'sandybrown'=> 'F4A460',
        'seagreen'=> '2E8B57',
        'seashell'=> 'FFF5EE',
        'sienna'=> 'A0522D',
        'silver'=> 'C0C0C0',
        'skyblue'=> '87CEEB',
        'slateblue'=> '6A5ACD',
        'slategray'=> '708090',
        'slategrey'=> '708090',
        'snow'=> 'FFFAFA',
        'springgreen'=> '00FF7F',
        'steelblue'=> '4682B4',
        'tan'=> 'D2B48C',
        'teal'=> '008080',
        'thistle'=> 'D8BFD8',
        'tomato'=> 'FF6347',
        'turquoise'=> '40E0D0',
        'violet'=> 'EE82EE',
        'wheat'=> 'F5DEB3',
        'white'=> 'FFFFFF',
        'whitesmoke'=> 'F5F5F5',
        'yellow'=> 'FFFF00',
        'yellowgreen'=> '9ACD32',
    
        // mango special colors=> #screw_mango
        'offwhite'=> 'FAF9F6',
        'sand'=> 'C2B280',
        'aquagreen'=> '00C0A3',
        'copper'=> 'b87333',
        'ochre'=> 'edb525',
        'pastelpink'=> 'F8C8DC',
        'coralred'=> 'ff4040',
        'mediumbrown'=> '7f5112',
        'cognac'=> '9A463D',
        'pastelgreen'=> '77DD77',
        'caramel'=> 'C68E17',
        'clementine'=> 'eb5e00',
        'mintgreen'=> '98ff98',
        'stone'=> 'B7B09C',
        'russet'=> '80461B',
        'blackdenim'=> '425267',
        'vanilla'=> 'F3E5AB',
        'burntorange'=> 'CC5500',
        'petrolblue'=> '216477',
        'lilac'=> 'C8A2C8',
        'strawberry'=> 'fc5a8d',
        'pastelyellow'=> 'FDFD96',
        'cherry'=> 'D2042D',
        'leather'=> '624a2e',
        'greenapple'=> '8db600',
        'bubblegumpink'=> 'ffc1cc',
        'icegrey'=> 'e0e0de',
        'nightblue'=> '222d5a',
        'bleachblue'=> '00008B',
        'indigoblue'=> '4b0082',
        'mustard'=> 'FFDB58',
        'inkblue'=> '16264c',
        'tobaccobrown'=> '6d5843',
        'olivegreen'=> '808000',
        'darkheathergrey'=> '46220b',
        'pastelorange'=> 'FAC898',
        'mediumheathergrey'=> '9aa297',
        'palepink'=> 'fadadd',
        'opengrey'=> '808080',
        'nude'=> 'E5D2C4',
        'openblue'=> '0297DB',
        'peach'=> 'FFE5B4',
        'vibrantblue'=> '0022EE',
        'denimgrey'=> '304560',
        'openbeige'=> 'F5F5DC',
        'minkgrey'=> '8B807E',
        'charcoal'=> '36454F',
        'neonorange'=> 'FF5F1F',
        'neonpink'=> 'FF10F0',
        'lightheathergrey'=> 'cbbdb0',
        'darksilver'=> '71706E',
        'deepdarkblue'=> '00008b',
        'ivorywhite'=> 'FFFFF0',
        'openred'=> 'FF0000',
        'neonyellow'=> 'E0E722',
        'mediumgreen'=> '3cb371',
        'billiardgreen'=> '1e3628',
        'camel'=> 'c19a6b',
        'wine'=> '722F37',
        'mediumgrey'=> '939799',
        'grapefruit'=> 'e0707c',
        'chinablue'=> 'a5e3f9',
    
        // turkish-colors
        'mercankırmızısı'=> 'ff4040',
        'çimrengi'=> '006400',
        'kırıkbeyaz'=> 'FAF9F6',
        'gökmavisi'=> '87CEEB',
        'açık/pastelgri'=> 'D3D3D3',
        'mandalina'=> 'CC5500',
        'hakirenk'=> 'F0E68C',
        'ekrü'=> 'C2B280',
        'pastelsarı'=> 'FDFD96',
        'ortakahverengi'=> '7f5112',
        'donukmavi'=> '216477',
        'yanıkturuncu'=> 'CC5500',
        'gümüşrengi'=> 'C0C0C0',
        'suyeşili'=> '98FB98',
        'kırmızı'=> 'FF0000',
        'naneyeşili'=> '98ff98',
        'buzgrisi'=> 'e0e0de',
        'çikolata'=> 'D2691E',
        'koyumavi'=> '00008B',
        'şekerpembe'=> 'ffc1cc',
        'mavi'=> '0000FF',
        'yeşil'=> '2E8B57',
        'açıkmavi'=> 'ADD8E6',
        'siyahdenim'=> '425267',
        'ortakırçıllıgri'=> '9aa297',
        'bakırrengi'=> 'b87333',
        'fuşya'=> 'FF00FF',
        'vanilyarengi'=> 'F3E5AB',
        'pastelpembe'=> 'F8C8DC',
        'açık/pastelmor'=> '800080',
        'lila'=> 'C8A2C8',
        'petrolmavisi'=> '216477',
        'pastelyeşil'=> '77DD77',
        'kızılkahverengi'=> 'BC8F8F',
        'konyakrengi'=> '9A463D',
        'tütünkahvesi'=> '6d5843',
        'koyueflatunrengi'=> '8B008B',
        'sarı'=> 'FFFF00',
        'çilekkırmızısı'=> 'fc5a8d',
        'şeftali'=> 'FFE5B4',
        'ağartılmışmavi'=> '00FFFF',
        'çivitmavisi'=> '4B0082',
        'kumbeji'=> 'C2B280',
        'tenrengi'=> 'E5D2C4',
        'koyuyeşil'=> '006400',
        'mürekkepmavisi'=> '16264c',
        'burgonyarengi'=> '8B0000',
        'hardalrengi'=> 'FFDB58',
        'denimgri'=> '304560',
        'kömürkarası'=> '36454F',
        'açık/pastelkahverengi'=> 'A52A2A',
        'vizonrengi'=> '8B807E',
        'pastelturuncu'=> 'FAC898',
        'pembemsituruncu'=> 'FF4500',
        'koyuturuncu'=> 'FF8C00',
        'kirazkırmızısı'=> 'D2042D',
        'zeytinyeşili'=> '808000',
        'koyusarı'=> '9b870c',
        'neonpembe'=> 'FF10F0',
        'karamel'=> 'C68E17',
        'gecemavisi'=> '191970',
        'açıkpembe'=> 'FFB6C1',
        'altınsarısı'=> 'FFD700',
        'yeşilelma'=> '8db600',
        'koyulacivert'=> '0B0B45',
        'uçukpembe'=> 'fadadd',
        'taşrengi'=> 'B7B09C',
        'menekşe'=> 'EE82EE',
        'neonsarı'=> 'E0E722',
        'ortagri'=> '939799',
        'fildişirengi'=> 'FFFFF0',
        'greyfurt'=> 'e0707c',
        'çinmavisi'=> 'a5e3f9',
        'açıkkırçıllıgri'=> 'b7b2af',
        'şaraprengi'=> '722F37',
    ];

    public function handle($name){

        $hex = "ff0000";
        $b = false;
        $name =  strtolower($name);
      

        $name = explode(" ", $name);
        foreach ($name as $word) {
            
            if(isset($this->colorMap[$word])){
                $hex = $this->colorMap[$word]; 
                $b=true;
                break;  
            }else{
                foreach ($this->colorMap as $key => $value) {
                    $key = strtolower($key);
                    if(str_contains($key,$word) || str_contains($word,$key) ){
                        $hex = $value; 
                        $b=true;
                        break;  
                    }
    
    
                }
            }

            if($b== true) break;

        }

        return $hex;
    }
}